//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adam.JSGenerator.Demonstration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Explanations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Explanations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Adam.JSGenerator.Demonstration.Explanations", typeof(Explanations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        body
        ///        {
        ///            color: InactiveCaptionText;
        ///        }
        ///        h2
        ///        {
        ///            font-size: 120%;
        ///            color: CaptionText;
        ///        }
        ///    &lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;h2&gt;
        ///        Using anonymous types&lt;/h2&gt;
        ///    &lt;p&gt;
        ///        Another way of expressing the properties of an object literal is by passing an object,
        ///        of which the public properties are foun [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AnonymousObjectLiteralsDemonstration {
            get {
                return ResourceManager.GetString("AnonymousObjectLiteralsDemonstration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        body
        ///        {
        ///            color: InactiveCaptionText;
        ///        }
        ///        h2
        ///        {
        ///            font-size: 120%;
        ///            color: CaptionText;
        ///        }
        ///    &lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;h2&gt;
        ///        Using fluent syntax&lt;/h2&gt;
        ///    &lt;p&gt;
        ///        A second way that object literals can be expressed is using a fluent syntax.&lt;/p&gt;
        ///    &lt;p&gt;
        ///        Note how both property names are quote [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FluentObjectLiteralsDemonstration {
            get {
                return ResourceManager.GetString("FluentObjectLiteralsDemonstration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;style type=&quot;text/css&quot;&gt;
        ///            body { color: InactiveCaptionText; }
        ///            h2 { font-size: 120%; color: CaptionText; }
        ///            .cf { font-family: Courier New; font-size: 10pt; color: black; background: white; }
        ///            .cl { margin: 0px; }
        ///            .cb1 { color: #2b91af; }
        ///            .cb2 { color: #a31515; }
        ///            .cb3 { color: blue; }
        ///        &lt;/style&gt;
        ///    &lt;/head&gt;
        ///	&lt;body&gt;
        ///	    &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ImplicitConversionsDemonstration {
            get {
                return ResourceManager.GetString("ImplicitConversionsDemonstration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;style type=&quot;text/css&quot;&gt;
        ///            body { color: InactiveCaptionText; }
        ///            h2 { font-size: 120%; color: CaptionText; }
        ///        &lt;/style&gt;
        ///    &lt;/head&gt;
        ///	&lt;body&gt;
        ///	    &lt;h2&gt;Generating Json&lt;/h2&gt;
        ///	    &lt;p&gt;Combining these techniques with LINQ allows us to generate JSON quite effectively.&lt;/p&gt;
        ///        &lt;h2&gt;Source:&lt;/h2&gt;
        ///
        ///&lt;style type=&quot;text/css&quot;&gt;
        ///.cf { font-family: Courier New; font-size: 10pt; color: black; backg [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JsonDemonstration {
            get {
                return ResourceManager.GetString("JsonDemonstration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        body
        ///        {
        ///            color: InactiveCaptionText;
        ///        }
        ///        h2
        ///        {
        ///            font-size: 120%;
        ///            color: CaptionText;
        ///        }
        ///    &lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;h2&gt;
        ///        Nested Types&lt;/h2&gt;
        ///    &lt;p&gt;
        ///        Passing an object, like an anonymous type, also supports recursion.&lt;/p&gt;
        ///    &lt;h2&gt;
        ///        Source:&lt;/h2&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        .c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NestedObjectLiteralsDemonstration {
            get {
                return ResourceManager.GetString("NestedObjectLiteralsDemonstration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        body
        ///        {
        ///            color: InactiveCaptionText;
        ///        }
        ///        h2
        ///        {
        ///            font-size: 120%;
        ///            color: CaptionText;
        ///        }
        ///    &lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;h2&gt;
        ///        Object Literals&lt;/h2&gt;
        ///    &lt;p&gt;
        ///        ObjectLiteralExpression objects contain an associative array of Expression objects
        ///        to Expression objects.&lt;/p&gt;
        ///    &lt;p&gt;
        ///        Ther [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ObjectLiteralsDemonstration {
            get {
                return ResourceManager.GetString("ObjectLiteralsDemonstration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        body
        ///        {
        ///            color: InactiveCaptionText;
        ///        }
        ///        h2
        ///        {
        ///            font-size: 120%;
        ///            color: CaptionText;
        ///        }
        ///    &lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;h2&gt;
        ///        Object Literals&lt;/h2&gt;
        ///    &lt;p&gt;
        ///        ObjectLiteralExpression objects contain an associative array of Expression objects
        ///        to Expression objects.&lt;/p&gt;
        ///    &lt;p&gt;
        ///        Ther [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ObjectLiteralsDemonstration1 {
            get {
                return ResourceManager.GetString("ObjectLiteralsDemonstration1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        body
        ///        {
        ///            color: InactiveCaptionText;
        ///        }
        ///        h2
        ///        {
        ///            font-size: 120%;
        ///            color: CaptionText;
        ///        }
        ///    &lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;h2&gt;
        ///        Operator Precedence&lt;/h2&gt;
        ///    &lt;p&gt;
        ///        The library takes care of operator precedence for you.&lt;/p&gt;
        ///    &lt;h2&gt;
        ///        Source:&lt;/h2&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        .cf
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OperatorPrecedenceDemonstration {
            get {
                return ResourceManager.GetString("OperatorPrecedenceDemonstration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;style type=&quot;text/css&quot;&gt;
        ///            body { color: InactiveCaptionText; }
        ///            h2 { font-size: 120%; color: CaptionText; }
        ///            .cf { font-family: Courier New; font-size: 10pt; color: black; background: white; }
        ///            .cl { margin: 0px; }
        ///            .cb1 { color: #2b91af; }
        ///            .cb2 { color: #a31515; }
        ///        &lt;/style&gt;
        ///    &lt;/head&gt;
        ///	&lt;body&gt;
        ///	    &lt;h2&gt;Parsing Identifiers&lt;/h2&gt;
        ///	    &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ParsedIdentifierDemonstration {
            get {
                return ResourceManager.GetString("ParsedIdentifierDemonstration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        body
        ///        {
        ///            color: InactiveCaptionText;
        ///        }
        ///        h2
        ///        {
        ///            font-size: 120%;
        ///            color: CaptionText;
        ///        }
        ///        table
        ///        {
        ///            font-size: 80%;
        ///            width: 100%;
        ///            border: 1px solid #ddd;
        ///        }
        ///        td
        ///        {
        ///            background-color: #eee;
        ///        }
        ///        .cf
        ///        {
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SimpleArithmeticDemonstration {
            get {
                return ResourceManager.GetString("SimpleArithmeticDemonstration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;style type=&quot;text/css&quot;&gt;
        ///            body { color: InactiveCaptionText; }
        ///            h2 { font-size: 120%; color: CaptionText; }
        ///            .cf { font-family: Courier New; font-size: 10pt; color: black; background: white; }
        ///            .cl { margin: 0px; }
        ///            .cb1 { color: #2b91af; }
        ///            .cb2 { color: #a31515; }
        ///        &lt;/style&gt;
        ///    &lt;/head&gt;
        ///	&lt;body&gt;
        ///	    &lt;h2&gt;Simple Identifiers&lt;/h2&gt;
        ///	    &lt;p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SimpleIdentifierDemonstration {
            get {
                return ResourceManager.GetString("SimpleIdentifierDemonstration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;style type=&quot;text/css&quot;&gt;
        ///            body { color: InactiveCaptionText; }
        ///            h2 { font-size: 120%; color: CaptionText; }
        ///        &lt;/style&gt;
        ///    &lt;/head&gt;
        ///	&lt;body&gt;
        ///	    &lt;h2&gt;Basics&lt;/h2&gt;
        ///	    &lt;p&gt;Any expression can be used as a statement. On top of that, the JS static class contains a lot of helper methods that allow you to quickly produce common JavaScript statements.&lt;/p&gt;
        ///        &lt;h2&gt;Source:&lt;/h2&gt;
        ///        &lt;p&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StatementsBasicsDemonstration {
            get {
                return ResourceManager.GetString("StatementsBasicsDemonstration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;style type=&quot;text/css&quot;&gt;
        ///            body { color: InactiveCaptionText; }
        ///            h2 { font-size: 120%; color: CaptionText; }
        ///        &lt;/style&gt;
        ///    &lt;/head&gt;
        ///	&lt;body&gt;
        ///	    &lt;h2&gt;Welcome!&lt;/h2&gt;
        ///	    &lt;p&gt;Please select a demonstration from the list on the left.&lt;/p&gt;
        ///    &lt;/body&gt;
        ///&lt;/html&gt;
        ///.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
